BasicBankingSystem/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
   path('admin/', admin.site.urls),
   path('',include("customer.urls")),
]

customer/urls.py
from django.urls import path, include
from . import views

app_name = 'customer'
urlpatterns = [
   path('',views.home,name='home'),
   path('information/',views.information,name='information'),
   path('transfer_money/',views.transfer_money,name='transfer_money'),
   path('contact/',views.contact,name='contact'),
]

customer/models.py
from django.db import models
from django.core.validators import MinLengthValidator

# Create your models here.
class Customer(models.Model):
    name = models.CharField(max_length=100)
    email_id = models.CharField(max_length=100)
    mobile_no = models.CharField(max_length=10)
    balance = models.IntegerField(default=0)
    account_no = models.IntegerField()

customer/views.py
from django.shortcuts import render,redirect
from .models import Customer
from django.db.models import Q
from django.contrib import messages

# Create your views here.
def home(request):
    return render(request,'home.html')

def information(request):
    if 'search' in request.GET:
        query = request.GET['search']
        customer_list = Customer.objects.all().filter(Q(name__icontains = query))
        return render(request,'information.html',{'customer_list':customer_list})
    else:
        customer_list = Customer.objects.all()
        return render(request,'information.html',{'customer_list':customer_list})

def transfer_money(request):
    if request.method == 'POST':
        acc1 = request.POST['acc1']
        acc2 = request.POST['acc2']
        amount = request.POST['amount']
        c1 = Customer.objects.all().filter(account_no=acc1).first()
        c2 = Customer.objects.all().filter(account_no=acc2).first()
        if(c1.balance >= int(amount)):
            b1 = c1.balance - int(amount)  
            b2 = c2.balance + int(amount)
            c1.balance = b1
            c1.save()
            c2.balance = b2
            c2.save()
            messages.success(request,'Successfully transfer is done!')
            return render(request,'transfer_money.html')
        else:
            messages.success(request,'Not sufficient balance')
            return render(request,'transfer_money.html')
    return render(request,'transfer_money.html')




def contact(request):
    return render(request,'contact.html')

customer/templates/contact.html
{% load static %}
<html>

<head>
    <title>information</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'customer/contact.css' %}"/>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light justify-content-between">
        <a class="navbar-brand btn btn-outline-info" href="{% url 'customer:home' %}">
           Banking system
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggleExternalContent">
            <ul class="navbar-nav">
                <li class="nav-item ml-2 mt-3 mb-3">
                <a class="btn btn-outline-info" aria-current="page" href="{% url 'customer:information' %}">Information</a>
                </li>
                <li class="nav-item ml-3 mt-3 mb-3">
                <a class="btn btn-outline-info" aria-current="page" href="{% url 'customer:transfer_money' %}">Transfer</a>
                </li>
                <li class="nav-item ml-3 mt-3 mb-3" >
                <a class="btn btn-outline-info" aria-current="page" href="{% url 'customer:contact' %}">ContactUs</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        <div class="row ">
            <div class="col-12" id="title">
                Online Banking System
            </div>
        </div>
        <br>
        <div class="row mt-3">
            <div class="col-12">
                <i class="fa fa-university fa-3x" aria-hidden="true"></i>
            </div>
            <div class="col mt-3" id="bankDetail">
                Bank name: xyz bank<br>
                IFSC code: 123xyz0
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-12" id="contact">
                Contact us
            </div>
            <div class="col-12 mt-3">
                <i class="fa fa-phone-square fa-2x mr-3" aria-hidden="true"></i>+91 99256700912
            </div>
            <div class="col-12 mt-3">
                <i class="fa fa-envelope fa-2x mr-3" aria-hidden="true"></i>xyz@gmail.com
            </div>
        </div>
        
    </div>
    


</body>

customer/templates/home.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <title>Home</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'customer/home.css' %}"/>
  <style>
    
  </style>
</head>

<body>
  <div class="row bg-light py-3" >
    <div class="col" id="titlecol">
      Basic Banking System  
    </div>
  </div>

  <div class="row flex-column" id="imagerow">
    <div class="col-4 my-2 mt-5">
      <a href="{% url 'customer:information' %}"><img class="img-responsive" src="static/i1.png"
          style="height: 100px; width:155px;"></a>
      <p>customer___information</p>
    </div>
    <div class="col-4 my-2">
      <a href="{% url 'customer:transfer_money' %}"><img class="img-responsive" src="static/tm1.png" style="height: 100px; width:155px;"></a>
      <p>Transfer___money</p>
    </div>
    <div class="col-4 my-2">
      <a href="{% url 'customer:contact' %}"><img class="img-responsive" src="static/c1.png" style="height: 100px; width:155px ;"></a>
      <p>contact___us</p>
    </div>
  </div>
  </div>
</body>

</html>

customer/templates/information.html
{% load static %}
<html>

<head>
    <title>Information</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'customer/information.css' %}"/>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light justify-content-between">
        <a class="navbar-brand btn btn-outline-info" href="{% url 'customer:home' %}">
           Banking system
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggleExternalContent">
            <ul class="navbar-nav">
                <li class="nav-item ml-2">
                <a class="btn btn-outline-info" aria-current="page" href="{% url 'customer:information' %}">Information</a>
                </li>
                <li class="nav-item ml-3">
                <a class="btn btn-outline-info" aria-current="page" href="{% url 'customer:transfer_money' %}">Transfer</a>
                </li>
                <li class="nav-item ml-3" >
                <a class="btn btn-outline-info" aria-current="page" href="{% url 'customer:contact' %}">ContactUs</a>
                </li>
            </ul>
            <form action="{% url 'customer:information' %}" class="form-inline" method="GET">
                <input class="form-control" type="search" placeholder="Search" aria-label="Search" name="search" >
                <button class="btn btn-outline-info" type="submit">Search</button>
            </form>
        </div>
    </nav>
    
    {% for customer in customer_list %}
    <ul class="list-unstyled" id="customer_list">
        <li class="media">
            <img class="img-responsive" src="../static/u1.png" style="height: 125px;width:110px;">
            <div class="media-body">
                <div id="attribute">Name: <a>{{customer.name}}</a><br>
                    Email ID: <a>{{customer.email_id}}</a><br>
                    Mobile no: <a>{{customer.mobile_no}}</a><br>
                    Account no: <a>{{customer.account_no}}</a><br>
                    Balance: <a>{{customer.balance}}</a>
                    
                </div>
            </div>
        </li>
    </ul>
    {% endfor %}
</body>

</html>

customer/templates/transfer_money.html
{% load static %}
<html>

<head>
    <title>Transfer</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'customer/transfer_money.css' %}" />
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light justify-content-between">
        <a class="navbar-brand btn btn-outline-info" href="{% url 'customer:home' %}">
            Banking system
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggleExternalContent">
            <ul class="navbar-nav">
                <li class="nav-item ml-2 mt-3 mb-3">
                    <a class="btn btn-outline-info" aria-current="page"
                        href="{% url 'customer:information' %}">Information</a>
                </li>
                <li class="nav-item ml-3 mt-3 mb-3">
                    <a class="btn btn-outline-info" aria-current="page"
                        href="{% url 'customer:transfer_money' %}">Transfer</a>
                </li>
                <li class="nav-item ml-3 mt-3 mb-3">
                    <a class="btn btn-outline-info" aria-current="page"
                        href="{% url 'customer:contact' %}">ContactUs</a>
                </li>
            </ul>
        </div>
    </nav>
    
    <form action="{% url 'customer:transfer_money' %}" method="POST">
        {% csrf_token %}
        
        <div class="container" style="width: 700px; margin-top : 70px">
           
                <div class="form-group">
                    <label for="acc1">From</label>
                    <input type="number" class="form-control" placeholder="Enter account No" name="acc1">
                </div>
                <div class="form-group">
                    <label for="acc2">To</label>
                    <input type="number" class="form-control" placeholder="Enter account No" name="acc2">
                </div>
                <div class="form-group">
                    <label for="amout">Amount</label>
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Enter amount" name="amount">
                        <div class="input-group-append">
                            <span class="input-group-text">₹</span>
                        </div>
                    </div>
                </div>
                <br>
                <div class="form-group">
                    <button class="btn btn-info" type="submit">Transfer now</button>
                </div>
            </div>
    </form>
</body>